### ISSUE TITLE
Fixing of slow_timeout in PaxosLogic

### ISSUE THREAD

**Issue by ArjunAhuja95** [florianmorath/piChain#4]
I do not understand why you are fixing the value of slow_timeout in line 618, what if rtt changes dramatically?

**Comment by florianmorath** [comment]
Thanks, you are right! 

What should be fixed is the randomly chosen backoff time r of a slow node such that only one slow node will create a block in expectation.
A slow node waits for 2R + r · 0.5R + 2epsilon, where r is a value chosen uniformly at random in [0, n + 1], R is the expected round-trip time and n the number of nodes in the system.
